apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: smart-factory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: smart-factory-api:local
        ports:
        - containerPort: 5000